//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartSprite.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UnityMetaFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnityMetaFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smartSprite.Templates.UnityMetaFile", typeof(UnityMetaFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileFormatVersion: 2
        ///guid: [guid-without-trace]
        ///folderAsset: yes
        ///timeCreated: 1450310219
        ///licenseType: Free
        ///DefaultImporter:
        ///  userData: 
        ///  assetBundleName: 
        ///  assetBundleVariant: .
        /// </summary>
        internal static string EmptyGameObject {
            get {
                return ResourceManager.GetString("EmptyGameObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileFormatVersion: 2
        ///guid: [guid-without-trace]
        ///timeCreated: 1450637947
        ///licenseType: Free
        ///TextureImporter:
        ///  fileIDToRecycleName: {}
        ///  serializedVersion: 2
        ///  mipmaps:
        ///    mipMapMode: 0
        ///    enableMipMap: 1
        ///    linearTexture: 0
        ///    correctGamma: 0
        ///    fadeOut: 0
        ///    borderMipMap: 0
        ///    mipMapFadeDistanceStart: 1
        ///    mipMapFadeDistanceEnd: 3
        ///  bumpmap:
        ///    convertToNormalMap: 0
        ///    externalNormalMap: 0
        ///    heightScale: .25
        ///    normalMapFilter: 0
        ///  isReadable: 0
        ///  grayScaleToAlpha: 0
        ///  generateCubemap: 0
        ///  cube [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameObject2D {
            get {
                return ResourceManager.GetString("GameObject2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [guid-without-trace].
        /// </summary>
        internal static string GuidPlaceHolder {
            get {
                return ResourceManager.GetString("GuidPlaceHolder", resourceCulture);
            }
        }
    }
}
